### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/emacs-buttercup#10]
The test runner output should be colored, with passing specs/suites in green, failing ones in red, and pending ones in yellow.

It should be possible to disable this using a `--no-color` command line argument.

**Comment by jorgenschaefer** [comment]
From #27:

> - Green for successful tests
> - Red for failing tests
> - Orange for pending ones
> - Standard foreground for skipped ones.

**Comment by lunaryorn** [comment]
@jorgenschaefer I'd like to add that unlike #28 I think this will really become important for Flycheck.  We have about 400 ERT unit tests currently (not counting syntax checker integration tests which add another 100 or so). If we convert all of these to proper specs—which will increase the number of tests somewhat as many large tests should be split into multiple small specs— then we'll definitely need colours to keep the output comprehensible.

**Comment by ebpa** [comment]
Note that not all terminals/outputs support color control characters.  Conditionally enabling color ("auto") according to an inference based on the file descriptor / environment variables / other information can save users from confusion.  Many utilities like grep (which has the option --color=[never|always|auto]) implement this behavior.  The logic in this JavaScript project may be helpful: [chalk/supports-color](https://github.com/chalk/supports-color) (specifically [index.js](https://github.com/chalk/supports-color/blob/master/index.js)).

**Comment by snogge** [comment]
Should this issue be closed now?

**Comment by jorgenschaefer** [comment]
Yep, thank you!
