### ISSUE TITLE
Add :custom-var keyword that works like :var for custom variables

### ISSUE THREAD

**Issue by DarwinAwardWinner** [jorgenschaefer/emacs-buttercup#102]
The proper way to set a variable that has been declared with `defcustom` is by calling `customize-set-variable`. The `:var` form should either be modified to use this for custom variables (including resetting them to their old value after a test), or another form `:custom-var` should be added that does so.

**Comment by jorgenschaefer** [comment]
Hm. I am confused. The whole point of the `:var` form is to avoid nesting when using a `let` form – it's not meant to change global variables or anything. If that is needed, people can do so in a `before*` block. `let` does not run customize code, either. Why would `:var`?

**Comment by DarwinAwardWinner** [comment]
The reason to use `customize-set-variable` is that some custom variables are set up to run a setter function when set, which actually implements the desired behavior. For example, enabling a minor mode also typically runs some setup code for that mode. When I'm testing packages with custom variables, I want to test the package under different values of these variables to make sure all the options work, instead of just using the defaults. In addition, I want all these variables to start out at their default values for each test, not whatever the user has customized them to, or else the test results would depend on user customizations. Then after the test finishes, I need to restore all those variables to the user's customized values, so that if someone runs buttercup within their existing Emacs session, it doesn't mess up all their custom settings.

Here's the code I'm currently using for this: https://github.com/DarwinAwardWinner/ido-completing-read-plus/blob/master/tests/test-ido-completing-read%2B.el#L117-L136 with the associated functions defined here: https://github.com/DarwinAwardWinner/ido-completing-read-plus/blob/master/tests/test-ido-completing-read%2B.el#L16-L109. That's probably a little more code than is necessary, but hopefully it demonstrates what I have in mind.

**Comment by jorgenschaefer** [comment]
> if someone runs buttercup within their existing Emacs session

I  would recommend simply not doing this. Emacs has so much global state that it's basically impossible to avoid that influencing tests. Or tests influencing the existing session.

As you mention, using customize to set a variable can run code. It's impossible to know if you can undo that code in any way, or if setting the "original" value will do anything at all. Best to be explicit here instead of hoping for the best.

I don't think using customize here is the right way to do things.

**Comment by DarwinAwardWinner** [comment]
Well, at some point, you have to assume that the setter for a custom variable is implemented sanely, in such a way that it always produce the same effect when called with a given value. If it didn't, then that variable would not be very useful as a customizable option. Still, I can see the argument for this being out of scope for buttercup.

An alternative that might make more sense to implement within buttercup would be an "around-each" form that works similarly to around advice. Something like:

```elisp
(around-each
 (let ((orig-value my-custom-variable))
   (unwind-protect
       (progn
         (customize-set-variable 'my-custom-variable (eval (car (get var 'standard-value))))
         TEST-BODY)
     (customize-set-variable 'my-custom-variable orig-value))))
```

Obviously TEST-BODY would be replaced with the code in each test spec (or possibly a call to the test spec wrapped in a closure to preserve correct lexical scope). This kind of thing is harder to set up properly using `before-each` and `after-each`, because you have to split it up into two separate forms.

**Comment by jorgenschaefer** [comment]
> Well, at some point, you have to assume that the setter for a custom variable is implemented sanely, in such a way that it always produce the same effect when called with a given value.

There is actually no implicit contract anywhere that this would be the case. Custom variables are weird.

`:var` is like `let`, and `let` does not run setters. I am not going to change my mind on this.

On the other hand, I really like the idea of `around-each`. Elisp, for better or worse, does a lot of nesting, and this is a way to deal with this nesting. Probably something like this?

```
(around-each body
  ...
  body
  ...)
```

(Explicitly naming the parameter feels nice to me, but I might be biased by hygienic macros in Scheme.)

**Comment by DarwinAwardWinner** [comment]
I see that `before-each` and `after-each` have a debug declaration. Do you happen to know what the declaration would be for `around-each`? Here's my best guess:

```elisp
(defmacro around-each (name &rest body)
  (declare (indent 1) (debug (&define sexp def-body)))
  ...)
```

**Comment by DarwinAwardWinner** [comment]
Looking further into this, it looks like I would basically have to reimplement nadvice.el from scratch in order to properly implement `around-each`, so I think I'm going to drop this.
