### ISSUE TITLE
"spy-on" fails for autoloaded functions and breaks commands

### ISSUE THREAD

**Issue by DarwinAwardWinner** [jorgenschaefer/emacs-buttercup#103]
When one of my tests runs `spy-on` on an autoloaded function that hasn't been loaded yet, I get an error of:

```
error: (wrong-type-argument symbolp (autoload "find-func" 1050730 t nil))
```

Loading the package in question before calling `spy-on` fixes the problem. I suggest that `spy-on` should check if its target is an autoloaded function and call `autoload-do-load` on it if so, before setting up the spy. Alternatively, `spy-on` could use the Emacs advice system, which knows how to handle functions that haven't been loaded yet.

Similarly, if `spy-on` is called on a command, the spy won't be considered a command, and any test expecting it to be one will fail. The fix this, the spy should inherit the target's interactive form, unless the spy options provide another one.

**Comment by jorgenschaefer** [comment]
Supporting autoloading (and commands) sounds like a very good idea indeed!

**Comment by snogge** [comment]
Wasn't this fixed by jorgenschaefer/emacs-buttercup#95 ?

**Comment by snogge** [comment]
@DarwinAwardWinner , isn't this issue fixed by #95?

**Comment by DarwinAwardWinner** [comment]
Yes, it should be fixed. Sorry for not replying to your previous ping. I guess it got lost in my inbox.

**Comment by DarwinAwardWinner** [comment]
I believe #95 also adds a test for this as well.
