### ISSUE TITLE
spy-on :and-return-value evals its argument

### ISSUE THREAD

**Issue by snogge** [jorgenschaefer/emacs-buttercup#104]
The rewrite of spy-on in jorgenschaefer/emacs-buttercup@6ad9565cd7adc195f81bdbbc1115a6bd96802a72 broke any spy-on :and-return-value that returned a cons, list, or quoted symbol:

```emacs-lisp
(spy-on test-function :and-return-value '(a list of symbols))
```
will bind test-function to 
```emacs-lisp
(lambda () (a list of symbols))
```
which will fail with ```(invalid-function a)```

**Comment by vspinu** [comment]
That change broke a large number of tests in [cider](https://travis-ci.org/clojure-emacs/cider/jobs/268657977). 

cc @DarwinAwardWinner
