### ISSUE TITLE
Was there a breaking change recently? We're seeing surprising failures in Flycheck.

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#111]
Hi there,

We're seeing all our Flycheck builds fail for reasons that seem related to buttercup. Maybe a breaking change was announced and I missed the memo?

```
Traceback (most recent call last):
  (progn (buttercup-expect (function (lambda nil (quote flycheck-haskell-mod...
  (buttercup-expect (closure (t) nil (quote flycheck-haskell-module-re) flyc...
  (buttercup--apply-matcher :to-match-with-group ((closure (t) nil (quote fl...
  (apply (closure (t) (re s index match) (let* ((matches\? (string-match re ...
  ((closure (t) (re s index match) (let* ((matches\? (string-match re s)) (r...
  (let* ((matches\? (string-match re s)) (result (and matches\? (match-strin...
  (string-match (closure (t) nil (quote flycheck-haskell-module-re) flycheck...
error: (wrong-type-argument stringp (closure (t) nil (quote flycheck-haskell-module-re) flycheck-haskell-module-re))
```

https://travis-ci.org/flycheck/flycheck/builds/271124030

Is this intentional? Are there docs somewhere about migration paths? Sorry if I missed something obvious — I haven't had much time to look into it yet.

Thanks! (cc @fmdkdd)

**Comment by fmdkdd** [comment]
I think 929a904debd4cf5846bbcb7e3c9ee21f7636c5bb is the likely culprit, since flycheck defines its own matches, and that commit says that matchers should now accept closures.

The solution on flycheck's end is to update the matchers, or use a previous version of buttercup (but blocked by cask/cask/issues/395, unfortunately).

**Comment by fmdkdd** [comment]
We've updated our matchers to accept closures (see flycheck/flycheck#1320), so I guess it's all good on our end.

We had one test that relied on defaults matchers not modifying the match data, but now they do. While it can be worked around, the former API made this effortless, as we wrote:
```emacs-lisp
  (expect (looking-at ...) :to-be-truthy)
  (expect (match-string 1) :to-equal ...)
```
Whereas now we have to save these values beforehand:
```emacs-lisp
  (let ((matches? (looking-at ...))
           (match (and matches? (match-string 1))))
       (expect matches? :to-be-truthy)
       (expect match :to-equal ...))
```
Maybe you'd want to add `save-match-data` around the string-match calls in `buttercup-define-matcher-for-unary-function` (same for the binary variant)?

**Comment by DarwinAwardWinner** [comment]
Looks like this might be a bug in code that I wrote, so I'll put this here to remind myself to have a look at it later when I have time.

**Comment by jorgenschaefer** [comment]
Nice debugging, and sorry for the inconvenience.

The string-match calls should be fine, they happen at macro expansion time. What likely breaks things for you there are the calls to `format-spec`, which uses regexes internally …

I just pushed ad901b55 – can you check if that fixes the problem?

**Comment by fmdkdd** [comment]
@jorgenschaefer Yes, it looks like this fixes our use case.  Much nicer that way :)

Thank you for taking care of this.  :+1:   I think we are all good now.

**Comment by DarwinAwardWinner** [comment]
I think it's arguably a bug that `format-spec` clobbers the match data. We should probably report that to the Emacs bug tracker.
