### ISSUE TITLE
Updating buttercup to 1.9 breaks lua-mode tests

### ISSUE THREAD

**Issue by hillu** [jorgenschaefer/emacs-buttercup#120]
Hi,

Running `buttercup -L .` in a clean checkout of [lua-mode](https://github.com/immerrr/lua-mode) with buttercup 1.9 fails some tests that pass using buttercup 1.8. For this, either version had been installed into a Debian/unstable system via the `elpa-buttercup` package. (AFAICS the Debian package makes no changes to the buttercup code.)

Some advice on how to further debug this would be appreciated.

Here's one of the tracebacks:
```
========================================
Test fill-paragraph fills single-line comment

Traceback (most recent call last):
  (let ((result-str (butlast (split-string (let ((temp-buffer (generate-new-...
  (butlast (split-string (let ((temp-buffer (generate-new-buffer " *temp*"))...
  (split-string (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-c...
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer ...
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (lua-...
  (unwind-protect (progn (lua-mode) (set (make-local-variable (quote lua-pro...
  (progn (lua-mode) (set (make-local-variable (quote lua-process)) nil) (set...
  (unwind-protect (progn (progn (let ((fill-column 10)) (lua-insert-goto-<> ...
  (progn (progn (let ((fill-column 10)) (lua-insert-goto-<> strs) (execute-k...
  (progn (let ((fill-column 10)) (lua-insert-goto-<> strs) (execute-kbd-macr...
  (let ((fill-column 10)) (lua-insert-goto-<> strs) (execute-kbd-macro (kbd ...
  (if look-at (progn (buttercup-expect (function (lambda nil (quote (point))...
  (progn (buttercup-expect (function (lambda nil (quote (point)) (point))) :...
  (buttercup-expect (lambda nil (quote (point)) (point)) :to-precede (lambda...
  (buttercup--apply-matcher :to-precede ((lambda nil (quote (point)) (point)...
  (apply (lambda (pos regexp) (save-excursion (goto-char pos) (let* ((preced...
  ((lambda (pos regexp) (save-excursion (goto-char pos) (let* ((precedes (lo...
  (save-excursion (goto-char pos) (let* ((precedes (looking-at regexp)) (sub...
  (goto-char (lambda nil (quote (point)) (point)))
error: (wrong-type-argument integer-or-marker-p (lambda nil (quote (point)) (point)))
```
This is essentially the same issue as described in [Debian bug #877398](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877398) which I was attempting to fix.

**Comment by jorgenschaefer** [comment]
The way matchers work has changed a bit to allow a much cleaner syntax for checking exception throwing. This was a backwards-incompatible change and I feel suitably bad for not making this more clear to users. Sorry about that.

I think it should work to update https://github.com/immerrr/lua-mode/blob/master/test/utils.el#L35-L47 to use `(funcall pos)` and `(funcall regexp)` to get the correct values.

**Comment by hillu** [comment]
@jorgenschaefer Thank you, with your advice I was able to patch the Debian package. You may want to document those breaking changes (and how to deal with them).

**Comment by jorgenschaefer** [comment]
You are correct. Added some entry to https://github.com/jorgenschaefer/emacs-buttercup/wiki – thank you, and I hope you continue to enjoy buttercup :-)
