### ISSUE TITLE
"spies" aren't scoped within "describe" blocks

### ISSUE THREAD

**Issue by gonewest818** [jorgenschaefer/emacs-buttercup#122]
I have three functions a, b, c and in their implementations a calls b, and b calls c.

In my tests I have something equivalent to

```
(describe "a"
  (spy-on 'b :and-return-value "dummy b")
  ... )

(describe "b"
  (spy-on 'c :and-return-value "dummy c")
  (let ((result (b)))
    (it "does whatever"
      (expect result :to-equal "something computed based on dummy c"))))
```

but when I execute the test I'm getting a failure in the "b" test case, because the result of `(b)` is coming back "dummy b".  It suggests spies aren't scoped to exist only within the `describe` or `it` block in which they are declared.

Can that be true? It seems like such a fundamental property of "spies" I can't understand how this hasn't been reported before.

**Comment by gonewest818** [comment]
On further experimentation, I think the `spy-on` directive has to occur within a `before-each` or `it`. They aren't scoped properly if they occur directly inside the `describe` as in my case above.

**Comment by jorgenschaefer** [comment]
That's true. What would you like to happen inside a `describe` block? An error?

**Comment by gonewest818** [comment]
To start with, perhaps a clarification in the docs (that the spy-on is scoped to the describe block only if it is nested within those certain special forms).

If there can be a warning or error then yes, that would made it even more clear. 

Thanks!

**Comment by jorgenschaefer** [comment]
Should be quite doable to throw an error in that case, thank you for the suggestion!

**Comment by bbatsov** [comment]
I was about to post a new issue when I found this one. I'm in the process of migrating Projectile's tests to buttercup and I was so puzzled that this wasn't working:

```
(describe "projectile-relevant-known-projects"
  :var 'known-projects
  (before-all
    (setq known-projects '("~/foo/" "~/bar/" "~/baz/")))
   (spy-on 'projectile-project-root :and-return-value "~/foo/")

  (describe "when projectile-current-project-on-switch is 'remove"
    (it "removes the current project"
      (let ((projectile-current-project-on-switch 'remove)
            (projectile-known-projects known-projects))
        (expect (projectile-relevant-known-projects) :to-equal '("~/bar/" "~/baz/")))))

  (describe "when projectile-current-project-on-switch is 'move-to-end"
    (it "moves the current project to the end of projectile-known-projects"
      (let ((projectile-current-project-on-switch 'move-to-end)
            (projectile-known-projects known-projects))
        (expect (projectile-relevant-known-projects) :to-equal '("~/bar/" "~/baz/" "~/foo/")))))

  (describe "when projectile-current-project-on-switch is 'keep"
    (it "returns projectile-known-projects"
      (let ((projectile-current-project-on-switch 'keep)
            (projectile-known-projects known-projects))
        (expect (projectile-relevant-known-projects) :to-equal '("~/foo/" "~/bar/" "~/baz/"))))))
```

Doesn't it make sense for spies to have `describe`-scope? Otherwise you waste a lot of time repeating yourself.

**Comment by bbatsov** [comment]
Btw, I'll also take an error if `spy-on` is misplaced - I just want to help others who might face the same issue as me. :-)

**Comment by jorgenschaefer** [comment]
I'm very much in favor of throwing an error for any "unusual" form in `describe` (i.e. not another `(x)describe`, `(x)it`, `before-*` or `after-*`). I'm currently really swamped with work, though, so any PR would be very welcome.

**Comment by gonewest818** [comment]
Thank you!
