### ISSUE TITLE
Redirecting warnings to 'Buttercup-Warnings' breaks existing tests; what's the fix?

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#124]
Hi,

I have a few tests to check that my code produces the right warnings, which look like this:

```
    (describe "-crossref--parse-search-results"
      (it "complains about non-ok statuses"
        (expect (shut-up
                  (display-warning "XYZ" 'xyz)
                  (shut-up-current-output))
                :to-equal "Warning (xyz): XYZ\n"))))
```

I recently updated Buttercup, and these tests are broken by the advice introduced in https://github.com/jorgenschaefer/emacs-buttercup/commit/929a904debd4cf5846bbcb7e3c9ee21f7636c5bb

> Another new feature is support for issuing warnings during tests. Any
> warning issued during a test is collected in a special buffer and
> displayed after the test finishes.

What's the new recommended way to test that a function produces the right warnings?

cc @DarwinAwardWinner 

Thanks!

**Comment by DarwinAwardWinner** [comment]
Hmm, I hadn't considered this use case, but let-binding `buttercup-warning-buffer-name` to the empty string (or any other string that isn't the name of a buffer) *inside* the test should suppress the warning-capturing behavior. Something like:

```elisp
(describe "-crossref--parse-search-results"
  (it "complains about non-ok statuses"
    (let ((buttercup-warning-buffer-name ""))
      (expect (shut-up
              (display-warning "XYZ" 'xyz)
              (shut-up-current-output))
            :to-equal "Warning (xyz): XYZ\n")))))
```

**Comment by DarwinAwardWinner** [comment]
More generally, maybe this should be implemented as a convenience macro, named something like `buttercup-suppress-warning-capture`?
