### ISSUE TITLE
Emacs jumps into "debug/error" window when test fails in interactive testing.

### ISSUE THREAD

**Issue by Fuco1** [jorgenschaefer/emacs-buttercup#14]
When I have a test where a spec fails and I run it using `buttercup-run-at-point`, two buffers pop at me: the butter cup report (yes, I want this!) and the emacs error/debug window (no, thanks emacs).

I'm not sure about the solution... maybe scan windows to see if such and such was opened, or wrap some code in `ignore-errors` (I do not yet fully understand how errors are evaluated/catched).

**Comment by jorgenschaefer** [comment]
Indeed, that sounds broken. Thanks!

**Comment by Fuco1** [comment]
Always nice to get a memo on half a year old report :D Thanks for working on this!

**Comment by jorgenschaefer** [comment]
You're welcome. And sorry for the delay, Circe's 2.0 release threw my schedule off :-)
