### ISSUE TITLE
:var is undocumented

### ISSUE THREAD

**Issue by alphapapa** [jorgenschaefer/emacs-buttercup#140]
I see `:var` used in several examples in the documentation, but the keyword itself is not documented.  It is not clear what it does or how.

**Comment by snogge** [comment]
Some documentation was added in #144.  Do you feel that is enough, @alphapapa?

**Comment by alphapapa** [comment]
@snogge Thank you, that seems good.  However, is there a benefit to using `:var` or `:var*` over using `let` or `let*` in the body form?  If the only benefit is the aesthetic of not using `let`, that should probably be mentioned.

**Comment by snogge** [comment]
@alphapapa , does #160 work for you?

**Comment by alphapapa** [comment]
Thanks!
