### ISSUE TITLE
Discovery fails if any parent directory is a dot-directory.

### ISSUE THREAD

**Issue by Fuco1** [jorgenschaefer/emacs-buttercup#15]
Buttercup helpfully filters tests in dot-directories, so that we won't run tests for packages installed via Cask in `.cask` directory.

However, if I have my project inside `/home/user/.dotdirectory/projects/my-project/tests` where `my-project` is the root of my project, no tests will run because they all match the `/.` of `/.dotdirectory`.

A solution is to cut away the current-directory to only do this filter inside the project directory.

**Comment by jorgenschaefer** [comment]
This is indeed pretty dumb of buttercup, thank you for the report!
