### ISSUE TITLE
Tests don't have expect is valid?

### ISSUE THREAD

**Issue by conao3** [jorgenschaefer/emacs-buttercup#151]
Hi!
I found the below test passed.
```elisp
(describe "A suite"
  (it "contains a spec with an expectation"
    (eq t t)))
```

```shell
$ make test
cask exec buttercup -L .
Running 1 specs.

A suite
  contains a spec with an expectation (0.91ms)

Ran 1 specs, 0 failed, in 0.0 seconds.
```

So I have questions.
- The test is valid?
- I can use any lisp predicates?
- Its behavior is spec? (I can use forever?)

**Comment by snogge** [comment]
Any spec with no asserts (and no other errors) will be considered as PASSED.
Note that 

    (describe "A suite"
      (it "contains a spec with an expectation"
        (eq t nil)))

should also pass.

- So while the test is valid, it is also kind of pointless.
- You can use more or less any emacs lisp code, but signals and exceptions will cause errors and/or failing cases. This is useful to call a set of functions and then use one or more asserts to validate the data. 
- I see no reason why this will ever change.

Please close the issue if you feel this answer is enough.

**Comment by conao3** [comment]
Good, thanks!!
