### ISSUE TITLE
Feature request: mockable file system?

### ISSUE THREAD

**Issue by Fuco1** [jorgenschaefer/emacs-buttercup#16]
I have no idea how to implement this properly, but it would be really cool if I could run tests inside a "faked file system".

Couple solutions:

One solution would be to mock all the functions for file-system access to operate over some known data... the problem is finding those functions and managing their interactions. Probably the most robust solution but I think pretty much impossible to implement.

Other solution: we could just create the requested file structure on the disc (say in `/tmp`), set the default directory there and let the code work normally.  The downside is that all the tested code would need to work with relative paths (which might not be that bad, most programs don't work with hard-coded paths anyway).

Some nice syntax to make directory structure and specify file content would also be cool.

**Comment by jorgenschaefer** [comment]
You mean some syntactic sugar for easily doing this?

```Lisp
(before-each
  (setq dir (make-temp-file "test-" t)
        default-directory dir))

(after-each
  (delete-directory dir t))
```

**Comment by Fuco1** [comment]
Well, more like something where you could specify the hierarchy in some
sort of lispy way:

```
(dir "contacts" 
 (file "contacts-friends" "Alice - 767 989 689\nBob - 890 334 636")
 (file "contacts-work" "Eve - 767 989 689\nDave - 890 334 636")
 (dir "stuff"
  (file "notes" "I need to write more tests!")))
```
 
So you can test your input/output on real files in a real structure.

**Comment by jorgenschaefer** [comment]
Ah, good idea. I wrote some code for that (in Python) for Elpy for just such a use case, I can totally see this being useful in Emacs, too.

**Comment by Fuco1** [comment]
I've implemented the following syntax

```elisp
(with-temp-fs
    '(("foo" "content")
      (dir "bar"
        "lol"
        (dir "qux"
          ("bux" "tralala")))
      "baz")
  ;; automatically sets `default-directory' to newly generated
  ;; directory in /tmp, afterwards the original is restored and the
  ;; teporary structure is deleted
  (with-temp-buffer
    (insert-file-contents "bar/qux/bux")
    (message "%s" (buffer-string))))  ;; => "tralala"
```

There are four "patterns"

* a string alone is taken as a filename to `touch`, that is, create an empty regular file with that name.
* a list of the form `(string string)` is taken as a filename and content of the file.
* a list of the form `(dir string patterns...)` is taken as a directory with name given by the second argument.  The rest of the patterns is recursively evaluated inside that directory.
* a list matching neither of above, `(patterns...)`, is recursed over and each pattern is evaluated separately.

The spec above creates following structure:

```
[15:26:15]matus@herakleitos:/tmp/temp-fs-6327GpO
> tree
.
├── bar
│   ├── lol
│   └── qux
│       └── bux
├── baz
└── foo

2 directories, 4 files
```

The rational is that files are created most often so it should be as simple as `("foo" "bar" "baz")` to create files.  The more specialized content you want, the more "annoying" the syntax gets.  Files with content come second and directories have to be specifically marked (but this gives us a bonus ability to `(put 'dir 'lisp-indent-function '1)` so they align nicely).

The syntax is extensible to further allow symlinks, with for example `(sym source target)` (hard and soft should both be possible), devices, pipes and all the other unix nonsense.

Tested on linux only, but uses emacs primitives so should work anywhere.  Depends on `f`.

Should I try to polish it somehow and include in buttercup, or do you think a spearate library would be better? (I would probably prefer it in bc because it gives the user all the tools right away without need to look for yet-another-testing-related-package).

**Comment by jorgenschaefer** [comment]
That looks a lot like the syntax I created for my own uses a while back, too (for Elpy). The syntax requires some more thought, I think. I mildly dislike the `dir` symbol there, but I do not know if there's something better

I would like this to be included in buttercup, but I do not want to add a mandatory dependency (`f.el`), as that pollutes the package list for testing. E.g. you won't notice if your dependencies are missing `f.el`; also, if `f.el` ever depends on Emacs version X.Y, you will not be able to test software with buttercup that can run of earlier versions. I have seen both with `ert-testrunner`, and I disliked that a lot.

The two solutions to this I can see would be either to get rid of the `f.el` dependency, if the places where it is used are easy to replace, or add a new file to the buttercup package that can be used, but requires the buttercup user to add the `f.el` dependency themselves.

Thoughts?

**Comment by Fuco1** [comment]
I can live without `f`, I used it mainly to make it faster to prototype this.  I agree that making this depend on newer emacs would be terrible (happens a lot in SP tests on newer modes... I still haven't figured out how to make Cask understand optional dependencies)

No good ideas about `dir` though.  The syntax might look a bit hairy.  Another solution would be to give each thing a "prefix" symbol... like OCaml/Haskell ADTs

**Comment by jorgenschaefer** [comment]
Hm. A file tree specification is either a string (empty file), a list of two elements where the second element is a string (non-empty file), or a list of two elements where the second element is a tree specification (subdir) – would that work? I.e.

```
("empty_file"
 "dir/empty_file"
 ("non_empty_file" "content")
 ("dir/anotherdir/non_empty_file" "tralala")
 ("big_dir" ("empty_file"
             ("non_empty_file" "content")
             "subdir/empty_file")))
```

**Comment by Fuco1** [comment]
This looks good.  Can we assume / always means subdirectory?  Well... even if unix allowed it (I don't know) I guess we could enforce it on the user.

This syntax is indeed a bit nicer to read.  Sometimes in `dired-hacks` I need to test symlinks, I think a nice extension then would be `("foo" -> "bar")` (dired displays links the same way, the name after `->` is the source to which we point, `"foo"` would be evaluated in the current context).

**Comment by jorgenschaefer** [comment]
I like that. :-)

And yes, `/` as well as `\x00` are not a valid characters in a file name under POSIX.

**Comment by Fuco1** [comment]
I've implemented the above syntax, with an addition of "foo/" meaning a directory, thus

    ("foo" "bar/")

will create a file `foo` and a directory `bar`.  Nesting works as in your example.

Next step is to figure out is how to include it in buttercup.  Do we want some special syntax available inside `it` or just a macro `with...`?

I still have to figure out how to replace `f-touch` as well... I'm surprised there isn't any mildly annoying way to do it in elisp (there are of course many quite annoying ways to do it :D)

**Comment by jorgenschaefer** [comment]
Something like this?

```Lisp
(if (file-exists-p path)
    (set-file-times path)
  (write-region "" nil path)))
```

(Do you actually need the `set-file-times` part? I suspect you are fine with just `write-region`)

**Comment by jorgenschaefer** [comment]
Forgot this part:

> Do we want some special syntax available inside it or just a macro with...?

I'd go with a separate macro first. If this turns out to be used a lot, we can think about adding more syntax, but I suspect that's not really necessary any time soon.

**Comment by Fuco1** [comment]
I looked at what `f-write-bytes` does and it seemed rather complex.  But then... all we need is an empty string :) I'm being silly.  All right, tomorrow I continue.

**Comment by jorgenschaefer** [comment]
Huh. `f-write-bytes` is incredibly convoluted, considering `write-region` does exactly that if `BEGIN` is a string …

**Comment by Fuco1** [comment]
How do you feel about `shut-up`? Seems like `write-region` spams an incredible amount of crap, and it's all C code ("wrote 0 bytes to ...")

**Comment by jorgenschaefer** [comment]
Meh. Same thing as with `f.el` – I'd rather not add more package dependencies.

If I remember correctly, you can't make `write-region` shut up anyhow because it uses deep C code, and emacs-devel refused to make it use anything more high-level because of safety reasons or something (need to be able to write backup files when Emacs crashes which should not call lisp)?

If shut-up.el can catch the message, though, we can probably do something like that. Otherwise, current trunk seems to do without that message. I can live with spurious messages in 24.x. Not nice, but what can we do.

**Comment by Fuco1** [comment]
Hey @jorgenschaefer!  I'm doing a bit of a cleanup :)  This (along with #37) now landed in assess and I'm fairly happy with how that works.  We could probably close the issues here, what do you think?

**Comment by jorgenschaefer** [comment]
Sounds good to me :-) Thank you!

**Comment by phst** [comment]
> If I remember correctly, you can't make write-region shut up anyhow

You can pass a value to VISIT that is neither nil nor t nor a string.
