### ISSUE TITLE
FR: run only the test marked with some kind of tag

### ISSUE THREAD

**Issue by sp3ctum** [jorgenschaefer/emacs-buttercup#21]
This feature would make it possible to pick a single test that is run, from the pool of all possible tests. Allowing running only a single test will help developers who do test driven development, by speeding their test execution when focusing on a single bug, as well as providing a clearer test output.

**Comment by sp3ctum** [comment]
I propose an additional `describe-solo` macro that adds itself into a global list of "solo" tests, in addition to calling `describe`. Then only these solo tests (tests marked with `describe-solo`) are ran.

**Comment by jorgenschaefer** [comment]
Good ideas! I think there are a few different things here, though.

First, it's very useful to be able to run only a single test. `buttercup-run-at-point` should help with this, but running the test in isolation with an external Emacs would be nicer still. To do this, buttercup could take a regular expression of what tests to run on the command line – do you think that would be helpful? `describe-solo` requires changing the code for the test you're actually interested in …

Second, tagging tests. It's sometimes useful to run only tests of a single type in a large test suite. Being able to tag them in some way would be nice. Similar to #5, we could add an argument to `describe` and `it` like so:

```Lisp
(describe "A tagged test"
  :tags (foo)
  (it "should only run when the test runner is passed the test tags"
    :tags (bar)
    ...))
```

What do you think?

**Comment by sp3ctum** [comment]
A regular expression for invoking the test run is a good solution, perhaps it will be simpler. :+1: 

Also I like your idea of a `:tags` better. This way it would work both for `describe` and `it`.

**Comment by sp3ctum** [comment]
I also realize having a unique tag will do the very same thing as having the "solo" test I proposed earlier. :)

**Comment by lunaryorn** [comment]
@jorgenschaefer Is there already an implementation of this feature?  I'm trying buttercup for Flycheck's test suite, as I really prefer its syntax over ERT, but not being able to run a subset of tests non-interactively is a show-stopper for me.  Flycheck has too large a test suite to run on every single change, and I frequently need to run tests for checkers of a specific programming language only.

**Comment by lunaryorn** [comment]
Actually, I'd already be happy if there was a way to run only specific suites, probably by some kind of sub-string matching on the suite name.

**Comment by jorgenschaefer** [comment]
I am afraid there is currently no implementation of this.

What I usually do when developing is to run just one test interactively. You can also restrict tests to be run by the directory to look in, or just load individual files. But that's all not exactly what you want, rather workarounds for a feature that is definitely missing.

I prefer the idea of substring/regexp matching for suites over adding tags as described earlier in this ticket. As someone who is actually requiring such a feature, would you say that tags would be better? I fear they might add useless verbosity to test declarations for something that's easily done with substring matches (as you say).

So, `buttercup` (the script) supporting a command line argument like `--only-matching REGEX`, and `buttercup--run-suite` only running tests that match this regexp, would solve this problem for you?

**Comment by lunaryorn** [comment]
@jorgenschaefer Yes, as I said: Matching on the names of suites is perfectly fine for me.

**Comment by jorgenschaefer** [comment]
I know you said that, I just wanted to make sure it's the preferred option and not just an acceptable hack :-) I'll see what I can do, thank you for the feedback!

**Comment by lunaryorn** [comment]
@jorgenschaefer Yes, a perfectly acceptable and preferable option, for sure!  The less syntax for tests, the better :relaxed:  Sorry for the misunderstanding!

**Comment by sp3ctum** [comment]
Awesome! :+1:
23.12.2015 4.08 ip. "Jorgen Schäfer" <notifications@github.com> kirjoitti:

**Comment by lunaryorn** [comment]
@jorgenschaefer Thank you very very much. :clap:   I'm going to start using buttercup for new tests in Flycheck, as it's definitely easier to write than ERT, and the last obstacle is gone now :heart_eyes:

**Comment by jorgenschaefer** [comment]
That's great news :-)

**Comment by lunaryorn** [comment]
@jorgenschaefer You're welcome :blush: Thank you very much for your great work on this :+1:

**Comment by lunaryorn** [comment]
@jorgenschaefer Oh Jesus, it's such an improvement over ERT: https://github.com/flycheck/flycheck/commit/114aa04ea0e6a4ae897de6b000a82bb163ddfe6f

Thank you very much!

**Comment by jorgenschaefer** [comment]
Awesome! All the good ideas are Jasmine's, though. :-D

Please do make issues for things you notice that could use improvement – having another person add opinions is extremely helpful. Thanks!

**Comment by lunaryorn** [comment]
@jorgenschaefer Will do, for sure.  I'm already collecting [custom matchers in `flycheck-buttercup.el`](https://github.com/flycheck/flycheck/blob/master/flycheck-buttercup.el).  There's only a few of them yet, but maybe some of them will be worth contributing to buttercup itself.

I also noticed two things that I'm missing compared to other BDD frameworks (scalacheck, specifically):

- Coloured output: https://github.com/jorgenschaefer/emacs-buttercup/issues/27
- Diffing `:to-equal` sides on failure: https://github.com/jorgenschaefer/emacs-buttercup/issues/28

**Comment by jorgenschaefer** [comment]
I'd like to add more generally-useful matchers. The ones in buttercup are mostly from Jasmine, and I think matchers are one of the main places where the differences between Emacs Lisp and JavaScript become apparent. E.g. your `:to-be-local` is a good example.

Looking at the definitions, I think buttercup also needs a more readable way to create the return values!

**Comment by lunaryorn** [comment]
> Looking at the definitions, I think buttercup also needs a more readable way to create the return values!

Indeed, the current syntax seems a little backwards: The `t` case has the "falsy" message?  It was a little confusing in the beginning, to be honest.

**Comment by jorgenschaefer** [comment]
> It was a little confusing in the beginning, to be honest.

Yes. I'd call it "terrible API". Too much of the internal structure showing there.
