### ISSUE TITLE
Is buttercup-pkg.el necessary?

### ISSUE THREAD

**Issue by akirak** [jorgenschaefer/emacs-buttercup#212]
Hello, the package description file is contained in this repository, but is there any reason you included it here?

You can delete it, because MELPA automatically generates the file.

If you put it in the repository, you need to get the format right. It is missing the dependencies field, so I think it should be

```emacs-lisp
(define-package "buttercup" "1.24"
  "Behavior-Driven Emacs Lisp Testing"
  '((emacs "24.3")))
```

**Comment by snogge** [comment]
I have no idea why the file was added, but I think we can live without
it.

**Comment by akirak** [comment]
Thanks!
