### ISSUE TITLE
Skipping specs and suites

### ISSUE THREAD

**Issue by lunaryorn** [jorgenschaefer/emacs-buttercup#22]
I'm trying to use Buttercup for Flycheck, and miss the ability to skip suites and specs programmatically.

Many of Flycheck's tests depend on the environment, i.e. whether a certain mode is installed or a certain program is present.  I'd like to be able to skip these tests when certain executables aren't present, etc.

I saw that I can just signal `buttercup-pending` to more or less achieve this, but actually I'd prefer to have a different error condition with a different output to differentiate between not-yet-implemented tests and tests that are skipped because certain conditions are not met.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion! For your use case, do you think it would be sufficient if test runners would interpret the argument to the `buttercup-pending` signal as a pending description, much like error descriptions, and emit that if it is set?

**Comment by lunaryorn** [comment]
@jorgenschaefer Sure, that'd also work.

**Comment by lunaryorn** [comment]
@jorgenschaefer Great, thank you very very much!
