### ISSUE TITLE
Buttercup gets stuck if :var not defined at beginning of body

### ISSUE THREAD

**Issue by wyuenho** [jorgenschaefer/emacs-buttercup#223]
The document doesn't mention anything about `:var` `:var*` have to be the top of a `describe` block or that they are exclusive of each other. If a `:var` is given after a `before-each`, buttercup is just stuck.

**Comment by snogge** [comment]
Thank you for the report @wyuenho .  Do you think this change will help?  Please try it out if you can, otherwise I will merge this within a few days.
