### ISSUE TITLE
Breaks with latest changes to format-spec

### ISSUE THREAD

**Issue by d12frosted** [jorgenschaefer/emacs-buttercup#225]
Seems like https://github.com/emacs-mirror/emacs/commit/5281946fbf6b3cdbec5ce82e0057c71849faf4d2 is breaking `buttercup-format-spec`. Whenever I run any test, I get the following error:

```
Traceback (most recent call last):
  buttercup-format-spec("Expected `%A' not to be `%f' to `%b', but it was." ...
  format-spec("Expected `%A' not to be `%f' to `%b', but it was." ((102 . eq...
  eq()
error: (wrong-number-of-arguments #<subr eq> 0)
```

**Comment by akirak** [comment]
I encounter this error too. It's currently a fatal error.

**Comment by snogge** [comment]
I've bumped the version tag, a new version should be available on NonGNU Elpa in a few hours.
