### ISSUE TITLE
Interactive testing ergonomics

### ISSUE THREAD

**Issue by zabe40** [jorgenschaefer/emacs-buttercup#227]
What is the preferred way to tell emacs to use `buttercup-minor-mode` for test files? I've been putting this at the top of my files:
```elisp
;;; -*- eval: (buttercup-minor-mode); lexical-binding: t; -*-
```
but it doesn't seem like the best answer.

Additionally, there isn't a minor-mode keymap for me to bind `buttercup-run-at-point` in. Adding one would be real convenient (though I've been working around it with this snippet)
```elisp
(defvar buttercup-minor-mode-map (make-sparse-keymap))
(add-to-list 'minor-mode-map-alist (cons 'buttercup-minor-mode buttercup-minor-mode-map))
```

**Comment by snogge** [comment]
Using file local variable eval statements (like you show above) is probably the best way.  I would put them at the end of the file, but that's just a matter of preference. 
I have a patch that adds the keymap https://github.com/snogge/emacs-buttercup/commit/e0ebdd6bb840ed365d6eba13fda5a3ee4b983412 , but there are some issues with the tests failing on Emacs master.

**Comment by snogge** [comment]
Merged and bumped the version.  Expect the new version to be available on NONGNU ELPA in a day or so.

**Comment by zabe40** [comment]
Thanks so much!!!
