### ISSUE TITLE
How to properly run all tests in a current buffer without using markdown with list code blocks?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [jorgenschaefer/emacs-buttercup#229]
Writing unit tests inside markdown code blocks weird because there is no syntax highlighting for lisp constructs inside code blocks and no completion. Maybe I don't understand smth but I've never seen such unit tests in Python, C#, JS.

**Comment by snogge** [comment]
The buttercup documentation is written in markdown with example tests in embedded code blocks. The markdown function runs all the tests in those blocks. So they are mostly a convenience for the maintainer.

Buttercup is not very good at running tests interactively, it's geared toward CI use. There is a function to run tests at point, but not the current buffer. I have not tried to write one, but I think it might be complicated to get right.  You are probably better off using a makefile and M-x compile.

**Comment by snogge** [comment]
Also have look at #221.

**Comment by snogge** [comment]
It seems the question has been answered for now so I will close this issue.
