### ISSUE TITLE
Native compilation problem when spying on certain primitives, such as file-exists-p

### ISSUE THREAD

**Issue by sergiodj** [jorgenschaefer/emacs-buttercup#230]
I'm investigating https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028725, which is a bug currently affecting Debian's and Ubuntu's flycheck packages, and noticed a strange behaviour when two `spy-on`'s are used sequentially but the first one has an `:and-return-value` parameter.

The following reproducer always triggers the bug for me on Debian sid with an upstream Emacs (`Development version b26d0dd58371 on master branch; build date 2023-02-26`):

``` elisp
(describe "Test buffer-file-name"
  (it "test"
    (spy-on 'file-exists-p :and-return-value t)
    (spy-on 'buffer-file-name)))
```

Here's what I see:

```
$ buttercup --eval "(package-initialize)" -L .
Running 1 specs.

Test buffer-file-name
  test  FAILED (11.68ms)

========================================
Test buffer-file-name test

Traceback (most recent call last):
  spy-on(buffer-file-name)
  buttercup--spy-on-and-call-replacement(buffer-file-name (lambda (&rest arg...
  comp-subr-trampoline-install(buffer-file-name)
  comp-trampoline-search(buffer-file-name)
  native-elisp-load("/home/sergio/.emacs.d/eln-cache/30.0.50-2895a91e/subr--...
error: (native-lisp-load-failed "file does not exists" "/home/sergio/.emacs.d/eln-cache/30.0.50-2895a91e/subr--trampoline-6275666665722d66696c652d6e616d65_buffer_file_name_0.eln")

Ran 1 specs, 1 failed, in 24.59ms.
buttercup-run failed: ""
```

I'm not entirely sure whether this is a problem with buttercup or with Emacs' recent native compilation feature, but I thought I'd report this here in case you have any ideas.  Thanks.

**Comment by sergiodj** [comment]
The following workaround works for me in Debian/Ubuntu:

```
buttercup --eval "(setq comp-enable-subr-trampolines nil)" -L .
```

For a recent build of upstream Emacs, the `comp-enable-subr-trampolines` variable was renamed:

```
buttercup --eval "(setq native-comp-enable-subr-trampolines nil)" -L .
```

**Comment by sergiodj** [comment]
I was able to determine that the problem doesn't seem to be on buttercup, so I filed https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-02/msg02464.html against upstream.

**Comment by snogge** [comment]
Thank you for pursuing this.  I haven't had the time to look into it myself at all yet.

**Comment by sergiodj** [comment]
My pleasure.

Note that the problem seems to be the redefinition of `file-exists-p` and other primitives that end up being used by the native compilation feature.  Upstream is coming up with a tentative solution for the problem, but I believe it's also a good idea to disable the generation of trampolines when native compilation is enabled.  I'm filing a PR to address this.
