### ISSUE TITLE
1.33 -> 1.34 update causes hangs in GNU Emacs >=30.0.50 (git)

### ISSUE THREAD

**Issue by xgqt** [jorgenschaefer/emacs-buttercup#243]
Hello!

I was investigating recent failures on the Gentoo CI server after buttercup update from 1.33 -> 1.34.

For reference:
- https://bugs.gentoo.org/926084
- https://bugs.gentoo.org/926083

On my machine's Emacs instead of having the above failures, buttercup hangs indefinitely.

Please ask for more info becasue I am not sure what information should I provide.

**Comment by snogge** [comment]
https://bugs.gentoo.org/926084 should be fixed by https://github.com/clojure-emacs/clojure-mode/pull/678

**Comment by xgqt** [comment]
@snogge 

Thanks a lot! I did not know that lack of lexical-bindign would manifest like that.

Would this always be the case with the error `(cl-assertion-failed ((eq closure (car-safe oclosure)) nil))`?

Btw, a qucik look at webrequest.el shows they do not have lexical-binding at all, and circe has only in some files.

Are you plannign to add a workaround for this for dynamic-binding? 
If not, should this issue be claosed?

**Comment by snogge** [comment]
And https://bugs.gentoo.org/926083 should be fixed by https://github.com/emacs-circe/circe/pull/416

**Comment by snogge** [comment]
> Thanks a lot! I did not know that lack of lexical-binding would manifest like that.

No, that was new for the Oclosures introduced in buttercup 1.34.  
Note that buttercup has been documented as requiring lexical binding for *test files*  for a long time https://github.com/jorgenschaefer/emacs-buttercup/blob/master/docs/writing-tests.md#its-just-functions , but it was only actually required if you used certain features. Now it is really mandatory. 

> Would this always be the case with the error `(cl-assertion-failed ((eq closure (car-safe oclosure)) nil))`?

The error will happen on all GNU Emacs 29.1 or newer, but it will look slightly different depending on the Emacs version.  As far as I can tell this is an assert from the Emacs implementation of Oclosures, not in buttercup itself. 

> Btw, a quick look at webrequest.el and circe shows they do not have lexical-binding at all, and circe's case it is only in some files.

I've fixed the tests on circe in https://github.com/emacs-circe/circe/pull/416 ,  I was not aware of the problems in webrequest.el, but as I said, it is only the test files that have to use `lexical-binding: t`.  Also, see #244 .

> Are you planning to add a workaround for this for dynamic-binding? If not, should this issue be closed?

There is no way to make buttercup work without lexical binding.  I will try to make it more obvious what the problem actually is, but I will track that work from #244. So feel free to close this bug if you are satisfied.

**Comment by xgqt** [comment]
@snogge 

> I will try to make it more obvious what the problem actually is, but I will track that work from #244. 

Thanks, I'm looking forward to this.

Will close this one.

**Comment by xgqt** [comment]
> Btw, a qucik look at webrequest.el and circe shows they do not have lexical-binding at all, and circe's case it is only in some files.

s/webrequest/webpaste/

for ref:
https://github.com/etu/webpaste.el/tree/main/tests

**Comment by snogge** [comment]
Thanks, I had a really hard time finding webrequest.el :)

**Comment by snogge** [comment]
Fix for webpaste.el https://github.com/etu/webpaste.el/pull/58 . All workflows are broken, so I have no idea about the test status.
