### ISSUE TITLE
buttercup issue with 1.34 change to use open closures on Emacs 29

### ISSUE THREAD

**Issue by ikappaki** [jorgenschaefer/emacs-buttercup#244]
With the upgrade to open closures in 1.34 for Emacs 29, the tests can now fail with a cryptic cl-assertion issue
```
traceback (most recent call last):
  cl--assertion-failed((eq 'closure (car-safe oclosure)))
error: (cl-assertion-failed ((eq 'closure (car-safe oclosure)) nil))
```

To reproduce
1. Checkout buttercup version 1.34 (e.g. in `c:\src\emacs-buttercup`)
2. Create a simple buttercup test `test-issue.el`
``` elisp
(require 'buttercup)

(describe "simple"
  (it "expect"
    (expect t :to-be t)))
```
3. Run buttercup run and discover from inside the directory where the test files is located, the test fails
``` shell
$ emacs --batch -L c:/src/emacs-buttercup -l buttercup -L . -f buttercup-run-discover .
Running 1 specs.

simple
  expect  FAILED (6.02ms)

========================================
simple expect

Traceback (most recent call last):
  cl--assertion-failed((eq 'closure (car-safe oclosure)))
error: (cl-assertion-failed ((eq 'closure (car-safe oclosure)) nil))

Ran 1 specs, 1 failed, in 6.21ms.
buttercup-run failed: ""
```

It appears the issue is caused by the missing lexical scoping, 
``` emacs-elisp
;; -*-lexical-binding:t-*-
(require 'buttercup)

(describe "simple"
  (it "expect"
    (expect t :to-be t)))
```

``` bash
$ emacs --batch -L c:/src/emacs-buttercup -l buttercup -L . -f buttercup-run-discover .
Running 1 specs.

simple
  expect (8.75ms)

Ran 1 specs, 0 failed, in 8.89ms.
```

Thanks

**Comment by snogge** [comment]
Lexical binding has been a requirement for buttercup test files for a long time see https://github.com/jorgenschaefer/emacs-buttercup/blob/master/docs/writing-tests.md#its-just-functions . Note that there is no requirement that the code under test have lexical binding enabled. 

I will make that more obvious in the documentation and see if it is possible to raise better errors so the user can immediately see that it is the lexical binding that is missing.

**Comment by vemv** [comment]
Hi,

I very recently started to see these failing my builds:

                 clj-refactor-pkg.el:1:1: Warning: file has no `lexical-binding' directive on its first line

Does it have anything to do with buttercup?

**Comment by snogge** [comment]
No, that warning is an Emacs 30 thing.  Emacs wants us all to use lexical-binding, and this is a step in that direction.
You can silence the warning by adding `-*- lexical-binding: nil; -*-` in a comment on the first line of the file. 
But I recommend converting your code to use lexical binding.

**Comment by snogge** [comment]
I've updated the buttercup documentation to mention that `lexical-binding: t` is mandatory in a more prominent space, and all code examples now have a lexical binding comment.

**Comment by vemv** [comment]
Thanks much for the info!

**Comment by snogge** [comment]
I just pushed a change to master that should cause tests that are loaded in files without lexical-binding raise an error. 
The `buttercup-run-discover` function will catch these errors and report them the same way as other read errors and report them as failed tests. Not sure how this will affect the various Emacs build frameworks that integrate with buttercup.

**Comment by snogge** [comment]
@doublep , you might want to check that I did not break anything in eldev.
@jcs090218 , same for Eask.

**Comment by snogge** [comment]
I don't know what I was thinking, those two last commits broke the tests.  I've reverted them and I'll get back to you once I've fixed that.

**Comment by snogge** [comment]
So I've updated the tests and pushed again.  The `describe` macro will now signal error `buttercup-dynamic-binding-error` if it is expanded with `lexical-binding` nil.
As mentioned above, the `buttercup-run-discover` function has special handling for these errors.
*I have not updated the version, so this change will not be available on ELPA yet.* 
I will close this issue now, please report any problems with this new solution as new issues. 
@doublep, @jcs090218, I hope I haven't messed things up for you.

**Comment by jcs090218** [comment]
Everything looks good to me: https://github.com/emacs-eask/cli/actions/runs/8404683838/job/23016562789?pr=239! Thanks for informing me!

**Comment by alphapapa** [comment]
> doublep , you might want to check that I did not break anything in eldev. jcs090218 , same for Eask.
> doublep, jcs090218, I hope I haven't messed things up for you.

@snogge Please keep me in the loop for changes like this.  [makem.sh](https://github.com/alphapapa/makem.sh) is used on all of my packages, as well as some maintained by other developers, and it supports Buttercup, which I also use on some of my packages (e.g. `org-ql` has over 400 tests in it).

It would probably be good to maintain a file in the repository listing various downstream projects which should be informed in advance of potentially breaking changes.

I don't know if the changes mentioned in this issue are related, but Guix has had to disable the tests for `org-ql` because Buttercup inexplicably hangs: https://git.savannah.gnu.org/cgit/guix.git/commit/gnu/packages/emacs-xyz.scm?id=3add97c7761e6c58a1d7405f417a49dda5f0a742

**Comment by snogge** [comment]
@alphapapa I will try to remember in the future.  I'm always worried that I will break someones tests.
