### ISSUE TITLE
Coloured output?

### ISSUE THREAD

**Issue by lunaryorn** [jorgenschaefer/emacs-buttercup#27]
While writing specs for Flycheck I noticed that it's—by design, of course—more verbose in its output than ERT.  Now, I really like that, because it's much more informative, but I think that the output could profit from ASCII colors being applied.  I think a simple scheme of four colours would be great:

- Green for successful tests
- Red for failing tests
- Orange for pending ones
- Standard foreground for skipped ones.

That'd help to get a quick idea and make failures stand out much more than they do currently, particularly if there are a lot of specs out of which just a single one failed.

What do you think?

**Comment by jorgenschaefer** [comment]
Thank you, I really like the idea. So much so I created #10 for it a while back! :-)

I'll close this so we can keep the discussion in one issue. (Duplicate tickets are not a problem, I'd rather have too many than too few :-))

**Comment by lunaryorn** [comment]
@jorgenschaefer Oh sorry, I admit that I didn't search the backlog before opening this issue :disappointed: Sorry for that.
