### ISSUE TITLE
Diffing results of :to-equal

### ISSUE THREAD

**Issue by lunaryorn** [jorgenschaefer/emacs-buttercup#28]
When matching large data structures with :to-equal the failure case output is not that helpful.  Buttercup simply dumps the left and right hand side entirely, and leaves it to the developer to sort out the difference.

Other test frameworks (e.g. scalatest) try to "diff" the output, e.g. make differences between both sides stand out.  I think it'd be great to have that in buttercup as well, specifically for strings and lists:
- For strings, a unified diff of both would be great
- For lists, it'd be great to elide all identical elements from the output and only show the different elements.

**Comment by lunaryorn** [comment]
Note that for my use case in Flycheck this is not particularly important: We'll most diff lists of Flycheck errors, which we can use a custom matcher for that can create a very specialised diff using our knowledge of the internals of the struct.

But it'd be nice to have, particularly when comparing buffer contents or something like that.

**Comment by jorgenschaefer** [comment]
Great idea.

For string diffs, Circe already comes with a diffing library I ported from Gauche Scheme: https://github.com/jorgenschaefer/circe/blob/master/lcs.el – I'm happy to move lcs.el to a separate package, though it probably needs a better name.

For list diffs, that's a bit more tricky, especially considering recursion. Python uses a somewhat dirty hack here which I think we could re-use: Just pretty-print the data structure and do a diff over the strings.

**Comment by lunaryorn** [comment]
> For list diffs, that's a bit more tricky, especially considering recursion. Python uses a somewhat dirty hack here which I think we could re-use: Just pretty-print the data structure and do a diff over the strings.

Why not? Pretty-printing of Emacs Lisp lists is quite regular; a diff of pretty printed representions of lists would surely be much better than the current output!

**Comment by cpitclaudel** [comment]
Neat idea! I was wishing for this as I tested a function that formatted BibTeX records :)

**Comment by DarwinAwardWinner** [comment]
One easy way to do this would be to load ert, run `(should (equal a b))`, and then parse the error raised, which looks something like:

```
(ert-test-failed
 ((should
   (equal
    '(1 2 3 4
        (5 6))
    '(1 2 3 4
        (5 7))))
  :form
  (equal
   (1 2 3 4
      (5 6))
   (1 2 3 4
      (5 7)))
  :value nil :explanation
  (list-elt 4
            (list-elt 1
                      (different-atoms
                       (6 "#x6" "?")
                       (7 "#x7" "?"))))))
```

**Comment by DarwinAwardWinner** [comment]
In fact, it might be possible to automatically convert any form with an ert explainer into a matcher in this way.

**Comment by DarwinAwardWinner** [comment]
I've implemented this in my expect-closures branch here: https://github.com/jorgenschaefer/emacs-buttercup/pull/100/commits/8a6288d0f4406b67d46ad83455e79f1842ac1f10
