### ISSUE TITLE
Testing calls to message

### ISSUE THREAD

**Issue by cocreature** [jorgenschaefer/emacs-buttercup#39]
While you can certainly argue that you should isolate the functions calling `message` and then only test the other functions, I think it would be nice to have some functionality for testing for a certain output that resulted from calls to `message`.
Sadly you can’t advice C primitives so the only way to record what `message` has written is probably to look in `*Messages*`. I don’t think it’s reasonable to expect that to be empty when running the test so either the position is recorded or the buffer is emptied before running the test.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question. The following works in Buttercup, is there something you are missing?

```Lisp
(defun my/messaging-function ()
  (message "Hello, World"))

(describe "A test for message"
  (before-each
    (spy-on 'message))
  
  (it "should intercept the message"
    (my/messaging-function)

    (expect 'message :to-have-been-called-with "Hello, World")))
```

**Comment by cocreature** [comment]
That is all I need, I just didn’t know it existed. I should have taken a closer look at the docs, thanks!
