### ISSUE TITLE
buttercup-pending signal message is not emitted

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/emacs-buttercup#44]
The buttercup-pending signal's message should be printed, not omitted. See https://github.com/jorgenschaefer/emacs-buttercup/commit/e6fd5f5b406e7f647ee8061487b73fe34aff4cb0#commitcomment-16743046

**Comment by lunaryorn** [comment]
@jorgenschaefer Please feel free to ask me if you need further information.  I must admit that I didn't investigate at all; I just noticed that my gpg-related tests in Flycheck appeared to pass even though I don't actually have gpg, but a little `(message)` call revealed that the test case itself doesn't actually run, so I presume the signal's message just got lost.

**Comment by lunaryorn** [comment]
Appears to be the same as #48, actually.  My suite has an `after-each` as well.

**Comment by jorgenschaefer** [comment]
Can you check if the fix for #48 fixes this issue as well?

**Comment by lunaryorn** [comment]
@jorgenschaefer Yes, it does.  The message from `assume` appears again.  Thank you very much for the quick fix :+1:

**Comment by jorgenschaefer** [comment]
Awesome! :-)
