### ISSUE TITLE
Expected failures?

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#46]
Hi Jorgen,

Is there support in buttercup for expected failures? As a way to document features to be implemented, for example. (I don't mean something like `xit`, since I'd like to know if changes suddenly make something work)

Thanks!

**Comment by jorgenschaefer** [comment]
Hello. You can invert `expect` clauses using `:not`, e.g. `(expect foo :not :to-equal bar)`. There is no support for "make sure that any of the expect clauses in this spec fail, but I do not care which". I don't think that's a good test, either. Make your expectations explicit. :-)

**Comment by cpitclaudel** [comment]
> There is no support for "make sure that any of the expect clauses in this spec fail, but I do not care which"

I'd rather like something like "make sure that all the expect clauses in this spec fail", in fact.

> I don't think that's a good test, either. Make your expectations explicit. :-)

I think the above is explicit. For me, it's a good way to document missing features and known bugs. For example:

```elisp
(describe "The implementation of a"
  (it-failing "should always return 0, not a random number > 0"
    (expect (a) :to-equal 0)))
```
 would give expected failures regardless of what `a` returns. This documents what should happen to `a` to make it properly, instead of documenting the broken behaviour.

**Comment by jorgenschaefer** [comment]
> This documents what should happen to `a` to make it properly, instead of documenting the broken behaviour.

You want to write a test for a feature you have not implemented yet, but you want that test not only to not fail, but you also want the test to fail if you ever get around to implementing the feature without adjusting the test first?

That still sounds very weird to me.

Buttercup does not do that right now, but you should be able to write an `it-failing` macro for your code base rather easily by inverting the body function, catching `buttercup-failed` when it runs and then not raising the function, or, if the signal is not raised, raising it.

Does that help?

**Comment by cpitclaudel** [comment]
> You want to write a test for a feature you have not implemented yet, but you want that test not only to not fail, but you also want the test to fail if you ever get around to implementing the feature without adjusting the test first?

It's sound weird when you put it that way, but it's a pretty common way of doing things, I think :) I sometimes use this pattern to keep a wish list; sometimes it's to document known bugs without polluting the output of the usual test suite. Many other frameworks have this: for example, erc has it (https://www.gnu.org/software/emacs/manual/html_node/ert/Expected-Failures.html); so do boost, python's unittest and pytest modules, and others :)

Of course, you can just say record the actual bug and add a comment next to it saying "the output of this should really be 'something else'", but that's not very nice.

**Comment by jorgenschaefer** [comment]
Yes, some other frameworks have this (together with oodles of other features). Jasmine, which Buttercup is based on, does not. I have never used such a feature. Do you have a concrete use case in an Emacs Lisp package you develop where you would need such a feature?

**Comment by cpitclaudel** [comment]
True, Jasmine doesn't :) Then maybe it's not a good idea to add them to buttercup.
The original use case was tests failing due to things that turned out to be buttercup bugs; I have one case where a function works on a keymap on which it will always be called, but it would be nice to generalize it to keymaps with submaps, and that currently fails. I've added it to the todo list instead, with the test in there.
