### ISSUE TITLE
after-each clauses hide spec failures

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#48]
Hey Jorgen,

Is anything wrong with this test? It passes in Emacs 25 on my machine.

```elisp
(describe "buttercup"
  (after-each (ignore))
  (describe "when using an after-each clause"
    (it "seems to expect nil to be truthy"
      (expect nil :to-be-truthy))))
```

Cheers,
Clément.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! There is nothing wrong with this test. It works fine if you comment out the `after-each` clause. Apparently, `after-each` hides failures – this is a bug in Buttercup. Thank you for noticing!

**Comment by lunaryorn** [comment]
@cpitclaudel @jorgenschaefer It'd appear that `after-each` swallows signals, because it hides `assume` (i.e. `buttercup-pending`) as well, see #44.
