### ISSUE TITLE
Spies are not properly removed

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#52]
The second test of the following suite fails:

```elisp
(defun a (&rest args)
  "A")

(describe "Buttercup"
  (describe "can register spies"
    (spy-on #'a :and-return-value "B")
    (it "to change return values"
      (expect (a) :to-equal "B")))
  (describe "doesn't extend spies beyond their enclosing describe"
    (it "thus a now returns 'A'"
      (expect (a) :to-equal "A"))))
```

But the documentation says

> A spy only exists in the describe or it block it is defined in, and will be removed after each spec.

Is that a bug?

**Comment by jorgenschaefer** [comment]
Hello! You should register spies in `before-each` clauses, not at the `describe` level. Does that solve the problem?

**Comment by cpitclaudel** [comment]
Oh, neat! Thanks!
