### ISSUE TITLE
Idea: show quoted from in error messages

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/emacs-buttercup#54]
It would be nice if the expect macro could record its unevaluated arguments, and print that in error messages: for example,

```
FAILED: Expected #[128 "\302\300\303\301\"\"\207" [biblio--throw-on-unexpected-errors (((http . 406) (url-queue-timeout . "Queue timeout exceeded"))) apply append] 6 "

(fn &rest ARGS2)"] to throw a child signal of url-error, not wrong-number-of-arguments
```

would be shown as

```
FAILED: Expected (apply-partially #'biblio--throw-on-unexpected-errors `(,http-error--alist ,timeout-error--alist)) to throw a child signal of url-error, not wrong-number-of-arguments
```

Btw, let me know if that's too much feedback in too little time! buttercup is really fun to work with, congratulations on this neat project :)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the idea! I have thought about this in the past, but I am quite unsure about it. For anything _but_ `:to-throw`, you really want to see the evaluated value as well. You can always get the original expression by looking at the source, but you have no way of knowing the resulting value.

So you'd end up with a pretty unwieldy error message for most cases.

I agree the situation for `:to-throw` is not exactly good, though. Maybe #41 can improve that somehow? I'm open for ideas.

> Btw, let me know if that's too much feedback in too little time! buttercup is really fun to work with, congratulations on this neat project :)

Thank you for the kind words! I'm of the opinion that it should always be ok to create issues. I might delay answering to some of them, though :-)

**Comment by DarwinAwardWinner** [comment]
To take an example, if I do:

```elisp
(expect (+ 1 1) :to-equal 3)
```

then the failure message is ``Expected 2 to `equal' 3``. What I would like to see is something more like ``Expected `(+ 1 1)' to `equal' 3 but it was 2 instead``. That message has the original expression, the expected value, and the observed value.

**Comment by DarwinAwardWinner** [comment]
I've written some code to implement this in #93.
