### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by dmh43** [jorgenschaefer/emacs-buttercup#64]
I have `(require 'emacs-tertestrial)` at the top of my test file with my dir structure as such:
├── Cask
├── README.org
├── emacs-tertestrial.el
└── tests
    └── emacs-tertestrial-test.el
and get "Cannot open load file: No such file or directory, emacs-tertestrial". When I call `cask exec buttercup`. I need to manually run an `add-to-list` on `load-path` to make sure the lib is found. Not too big of a deal but I was wondering if maybe I was missing something.

`cask exec buttercup -L` gives me `Args out of range: "", 1` no matter what.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Have you tried `cask exec buttercup -L .` (not the dot at the end, for the current directory)?

**Comment by dmh43** [comment]
How did I miss that :) Thanks.
