### ISSUE TITLE
Leverage el-mock

### ISSUE THREAD

**Issue by DamienCassou** [jorgenschaefer/emacs-buttercup#66]
Would it make sense for buttercup to leverage https://github.com/rejeep/el-mock.el instead of implementing something similar?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion. It might be possible, but I do not know why it would be desirable? Would reimplementing the current syntax in buttercup using el-mock not require more code than just implementing the actual functionality?

**Comment by DamienCassou** [comment]
I don't know but I supposed not. Moreover, `el-mock` has some features `emacs-buttercup` doesn't have.

**Comment by jorgenschaefer** [comment]
> I don't know but I supposed not.

Guess there's only one way to find out, eh? :-)

Buttercup tries to emulate Jasmine's syntax and functionality as close as possible. This includes the `spy-on` syntax, as well as being able to add mocks in `before-each` and `before-all` clauses. If that's possible to do with `el-mock` in a readable and maintainable way, I'd be fine with re-using that library.

**Comment by snogge** [comment]
I can't see anything in mock.el that cannot be done in buttercup.  Sometimes mock.el has an easier syntax, sometimes buttercup does. I'll close this issue as wontfix for now.
