### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by xendk** [jorgenschaefer/emacs-buttercup#69]
Buttercup is very nice indeed, but one thing I'm missing from other testing tools is colored output, like ecukes, for instance:

![selection_036](https://cloud.githubusercontent.com/assets/229422/23529954/ed8560ae-ff9f-11e6-928e-d93ba69fd8b9.png)

Apart from the visual appeal of colored output, a colorized summary line serves as a visual anchor that's easier to locate in the CI log or terminals.

One might also consider coloring the line of each test according to pass/fail, but that's probably a matter of taste.

**Comment by jorgenschaefer** [comment]
Yes, this would be really nice! Thank you for the idea. See #10 for the existing idea. I'll close this issue to keep the discussion in the existing one. :-)
