### ISSUE TITLE
Implement a `buttercup-runner` binary for `cask exec`

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/emacs-buttercup#7]
See [ert-runner](https://github.com/rejeep/ert-runner.el) and [cask exec](http://cask.readthedocs.org/en/latest/guide/usage.html#cask-exec).

Having this would be a bit more convenient than having to figure out the right arguments for the `emacs -batch` invocation.

**Comment by jorgenschaefer** [comment]
cask adds `<package>/bin` to `PATH`, so this should be easy:
http://cask.readthedocs.org/en/latest/guide/usage.html#cask-path
