### ISSUE TITLE
Can't install buttercup

### ISSUE THREAD

**Issue by psteckler** [jorgenschaefer/emacs-buttercup#71]
I'm running Emacs 24.5 on Linux Mint 18. When I run `M-x package-install buttercup`, I see:
      
`https://melpa.org/packages/buttercup-20160514.34.tar: Not found`

I have installed other Melpa packages successfully.

**Comment by jorgenschaefer** [comment]
I'm afraid I have no control whatsoever over the MELPA archive. Try `M-x package-refresh-contents`, and if that fails, report a problem with MELPA?

**Comment by psteckler** [comment]
Thanks, that worked!

**Comment by jorgenschaefer** [comment]
Nice! I hope you enjoy Buttercup :-)
