### ISSUE TITLE
Imenu generic expressions

### ISSUE THREAD

**Issue by Fuco1** [jorgenschaefer/emacs-buttercup#72]
I'm not sure how or where to add this (probably as an optional defun people could put on the elisp hook), but I've found useful to have imenu recognize suites/specs when I have larger test files.

```
(add-to-list 'imenu-generic-expression '("Test Suites" "\\((describe\\_> +\\)\"\\(\\_<.+\\_>\\)\"" 2))
(add-to-list 'imenu-generic-expression '("Spec" "\\((it\\_> +\\)\"\\(\\_<.+\\_>\\)\"" 2))
```

This works for me, right now I just add it to every elisp buffer but some people might not prefer that.  I'm not sure what is the proper convention.

**Comment by jorgenschaefer** [comment]
Nice, thank you! Maybe we need a buttercup-minor-mode?

**Comment by Fuco1** [comment]
Yea, that sounds reasonable.  I'll cook it up and send a PR.

**Comment by alphapapa** [comment]
> This works for me, right now I just add it to every elisp buffer but some people might not prefer that. I'm not sure what is the proper convention.

`use-package` does this as well, works really well!  :)
