### ISSUE TITLE
Detect same spec names

### ISSUE THREAD

**Issue by DamienCassou** [jorgenschaefer/emacs-buttercup#77]
Jasmine and buttercup both accepts similarly named specs:

```emacs
(describe "foo"
  (it "bar" ...)
  (it "bar" ...))
```

But, whereas Jasmine has [no-spec-dupes](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/no-spec-dupes.md) to detect duplicate specs, I don't know anything related for buttercup.

**Comment by DamienCassou** [comment]
I think detecting that a spec doesn't do any expectation would also be useful.

**Comment by jorgenschaefer** [comment]
Detecting dupes is a good idea! Not sure about "no expectations", I can see tests that simply avoid exceptions as somewhat useful, I guess. At least useful enough not to forbid them outright.
