### ISSUE TITLE
Issue to spy-on funcall?

### ISSUE THREAD

**Issue by etu** [jorgenschaefer/emacs-buttercup#82]
I'm currently migrating all the tests for [webpaste.el](https://github.com/etu/webpaste.el) from ert to buttercup. And I must say I'm very impressed by this nice framework you got here!

But I ran into a weird issue today while porting things. I made this commit: https://github.com/etu/webpaste.el/commit/4fb1521f847810e614d66bb69a95551b23fcb1ca

And as far as I know, the test in it self is fine and the function should do exactly that I expect. The test even works to run locally on my machine. (`cask install && make unit` if you'd like to try).

But then the weird thing. This doesn't work on travis, at all: https://travis-ci.org/etu/webpaste.el/builds/233320875

(Don't mind the build history on travis since I do a lot of rewriting of history while in my own branches, nobody other than me should be in **my** branch ;)).

So is there any weird things that might happen if you do `(spy-on 'funcall)` or is it something else at works here?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

The error indicates that something really bad is happening there. Probably Travis killing Emacs for memory or CPU consumption. As `funcall` is something that is even used inside Emacs for evaluation, I would not be surprised if this just does not work. There's also sadly very little Buttercup can do about it, it needs to be able to call functions. You can try `(spy-on 'funcall :and-call-through)`.

I'm not sure why it works locally and not on Travis. This might be related to byte compilation.

Though I would in general recommend against putting spies on such internal functions. You never know when a minor update somewhere kills everything. :-(

**Comment by etu** [comment]
Yeah, that makes sense. Made it like this instead https://github.com/etu/webpaste.el/commit/46da19799de01ae6838e17d54c114b4b33b9552f and that works better. Thanks!

**Comment by jorgenschaefer** [comment]
Great! Glad you like Buttercup, and please do not hesitate to open new issues if you have any other problems :-)
