### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DamienCassou** [jorgenschaefer/emacs-buttercup#83]
Would it make sense to tag current git commit so that users of melpa stable can benefit from latest improvements?

Thanks

**Comment by jorgenschaefer** [comment]
Yes, definitely. I originally intended to release a new version of Buttercup every 3 months, but I really failed at that, didn't I? :-(

**Comment by jorgenschaefer** [comment]
v1.7 tagged and pushed, thank you for the poke!
