### ISSUE TITLE
Don't reset a spy

### ISSUE THREAD

**Issue by DamienCassou** [jorgenschaefer/emacs-buttercup#84]
I expect this to pass:

```emacs
(defun foo ()  1)

(describe "testing"
  (describe "foo"
    (spy-on 'foo :and-call-fake (lambda () 2))
    (it "returns 2"
      (expect (foo) :to-be 2)))
  (describe "fooz"
    (it "returns 1"
      (expect (foo) :to-be 1 ))))
```

but it fails

```
testing
  foo
    returns 2
  fooz
    returns 1  FAILED

testing fooz returns 1
FAILED: Expected 2 to be `eq' to 1
```

**Comment by DamienCassou** [comment]
I think the problem comes from the fact that `buttercup-cleanup-functions` is filled while the [`describe` form is evaluated](https://github.com/jorgenschaefer/emacs-buttercup/blob/v1.7/buttercup.el#L377) and then reset when [the suite is ran](https://github.com/jorgenschaefer/emacs-buttercup/blob/v1.7/buttercup.el#L768) (through `buttercup-with-cleanup`). Why are suites executed immediately instead of being stored?

**Comment by jorgenschaefer** [comment]
The problem comes from using `spy-on` inside the `describe` clause and not inside a `before-all` or `before-each` block. Could you please use one or the other and try again? :-)

**Comment by DamienCassou** [comment]
I forgot to report you were right. You may close this issue now.
