### ISSUE TITLE
Automatic lambda with :to-throw

### ISSUE THREAD

**Issue by DamienCassou** [jorgenschaefer/emacs-buttercup#86]
Why do I have to wrap expressions in a lambda when using `:to-throw`? For example. the documentation says to write:

```emacs
(it "is for testing if a function throws an exception"
      (let ((bar (lambda () (+ a 1))))
        (expect bar :to-throw)))
```

but I would rather write:

```emacs
(it "is for testing if a function throws an exception"
      (expect (+ a 1) :to-throw))
```

I understand you want to stay close to jasmine. Is there another argument in favor of the current approach?

**Comment by jorgenschaefer** [comment]
No, there's even an issue for that: #41 :-)
