### ISSUE TITLE
--pattern isn't a file-name-pattern as the docs suggests

### ISSUE THREAD

**Issue by etu** [jorgenschaefer/emacs-buttercup#87]
Hello, I'm working on setting up tests that only run under certain conditions. For example only when Travis executes the build as a cron-job and not as a job triggered by a git push to the repo.

Then I was reading the docs here: https://github.com/jorgenschaefer/emacs-buttercup/blob/master/docs/running-tests.md#running-tests

Which suggested to me that I could name my file: `cron-test-webpaste.el` and have this file not mached by the regular tests. But that I could execute them like this:
```
cask exec buttercup --pattern 'cron-*.el' -L .
```

Then I found #30 and realized that `--pattern` is for a pattern of the `description` name. Why is this?

Either the docs or the implementation is wrong. I prefer the way it's documented, but I guess that's hard to change.

**Comment by jorgenschaefer** [comment]
Thank you for the report. This is outdated documentation, sadly – the test description pattern is more generic and useful in general for running individual tests … So the documentation should get updated.

**Comment by etu** [comment]
So, I have a bunch of `describe`'s, that starts with all different strings. And one `describe` that starts with `CRON:`.

Any suggestion on making the reverse of the following?
```
cask exec buttercup --pattern '^CRON:' -L .
```

I can add that Emacs doesn't seem to accept this:
```
cask exec buttercup --pattern '^(?!CRON:)' -L .
```

**Comment by jorgenschaefer** [comment]
Yeah, Emacs does not support negated regular expressions … An Emacs regexp for that would be `'^\([^C]\|C[^R]\|CR[^O]\)'` (you get the pattern). What is your use case here? I usually run all tests or, during development, some very narrow selection (ideally, one) of them …

**Comment by etu** [comment]
So... I have a bunch of test that should be executed every time on travis. And I'm about to implement a bunch that only should run once in a while. And preferably only on travis.

So my plan is to set up a travis cronjob and only run these tests if it's executed as a travis cronjob. How to detect this is simple since travis sets an env variable documented here: https://docs.travis-ci.com/user/cron-jobs/#Detecting-Builds-Triggered-by-Cron

The reason for these tests to not run all the time is because it will send requests to external sources which I don't want to spam to much. And It's not mockable since the purpose is to test if the external resource still works as expected. More about it here: https://github.com/etu/webpaste.el/issues/16

Also, that regex there works, except that it kills another test that begins with uppercase letter "C"... Maybe I'll write `cron` lowercase and have a rule that all descriptions should have an upcased first letter :D

**Comment by jorgenschaefer** [comment]
Can you split your tests into two directories, say `tests/unit/` and `tests/integration/` and pass one or the other to buttercup?

**Comment by etu** [comment]
Hmm, that would work. Good suggestion thanks 👍
