### ISSUE TITLE
Compatibility with old versions of Emacs

### ISSUE THREAD

**Issue by DamienCassou** [jorgenschaefer/emacs-buttercup#89]
Why do you keep compatibility with very old versions of Emacs (Emacs 24.1 is from 2012)? Buttercup is meant for Emacs package developers who are probably using recent versions of Emacs. If you care about Emacs developers using old Emacs versions, what about keeping compatibility with Emacs 24.5 instead of 24.1? Increasing minimum Emacs version would simplify the code base (e.g., cleaning of `-compat.el` and use of `cl-lib`) and reduce compile-time warnings (use of `define-error`).

**Comment by jorgenschaefer** [comment]
> Buttercup is meant for Emacs package developers who are probably using recent versions of Emacs.

Buttercup is meant to be able to automatically test packages that might want to run on older versions of Emacs. The Emacs version of the developer is pretty irrelevant there, really. :-)

I'm not opposed to dropping support for older Emacsen, though. "What is in Debian stable" or maybe even "what is in CentOS+EPEL" is probably a good cut-off line.

**Comment by DamienCassou** [comment]
Jorgen Schäfer <notifications@github.com> writes:
> Buttercup is meant to be able to automatically test packages 
> that might want to run on older versions of Emacs. The Emacs 
> version of the developer is pretty irrelevant there, really. :-) 


sometimes I should think more before writing :-).


> I'm not opposed to dropping support for older Emacsen, 
> though. "What is in Debian stable" or maybe even "what is in 
> CentOS+EPEL" is probably a good cut-off line. 


- Debian Jessie (previous stable) has emacs 24.4 (new stable has 
  24.5)
- CentOS has 24.3
- Ubuntu 14.04 LTS has emacs 24.3

If we target 24.3, it means we can clean a bit the -compat file 
and rely on cl-lib instead of cl. Does this sounds like a plan? 
I'm going on vacation for the next 3 weeks but can have a look at 
that when I'm back if you want. 

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jorgenschaefer** [comment]
24.3 works for me. Also, released over four years ago sounds "old enough" :-D Thank you for pushing this!
