### ISSUE TITLE
How to add helper utils .el files to the test directory? 

### ISSUE THREAD

**Issue by vspinu** [jorgenschaefer/emacs-buttercup#94]
What is the recommended way to add utility functions common to multiple test files? 

I have tried adding `my-test-utils.el` and then `(require 'my-test-utils)` but that fails with `no such file or directory` error. So tests dir is not added to the load path. Is this by design?

**Comment by jorgenschaefer** [comment]
Yes, this is by design, to prevent accidental inclusion of files. You can add more directories to find files in using the `-L` switch.

Does this help?

**Comment by vspinu** [comment]
Yes. Thanks!
